apiVersion: apps/v1
kind: Deployment
metadata:
  name: shard-manager
  namespace: shard-system
  labels:
    app: shard-manager
    component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shard-manager
  template:
    metadata:
      labels:
        app: shard-manager
        component: controller
    spec:
      serviceAccountName: shard-manager
      containers:
      - name: manager
        image: shard-controller/manager:latest
        imagePullPolicy: IfNotPresent
        command:
        - /manager
        args:
        - --config=/etc/config/config.yaml
        - --metrics-addr=0.0.0.0:8080
        - --health-addr=0.0.0.0:8081
        - --leader-elect=true
        ports:
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: shard-manager-config
      terminationGracePeriodSeconds: 30