//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HashRange) DeepCopyInto(out *HashRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HashRange.
func (in *HashRange) DeepCopy() *HashRange {
	if in == nil {
		return nil
	}
	out := new(HashRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthStatus) DeepCopyInto(out *HealthStatus) {
	*out = *in
	in.LastCheck.DeepCopyInto(&out.LastCheck)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthStatus.
func (in *HealthStatus) DeepCopy() *HealthStatus {
	if in == nil {
		return nil
	}
	out := new(HealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadMetrics) DeepCopyInto(out *LoadMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadMetrics.
func (in *LoadMetrics) DeepCopy() *LoadMetrics {
	if in == nil {
		return nil
	}
	out := new(LoadMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrationPlan) DeepCopyInto(out *MigrationPlan) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.EstimatedTime = in.EstimatedTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrationPlan.
func (in *MigrationPlan) DeepCopy() *MigrationPlan {
	if in == nil {
		return nil
	}
	out := new(MigrationPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardConfig) DeepCopyInto(out *ShardConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardConfig.
func (in *ShardConfig) DeepCopy() *ShardConfig {
	if in == nil {
		return nil
	}
	out := new(ShardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardConfigList) DeepCopyInto(out *ShardConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShardConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardConfigList.
func (in *ShardConfigList) DeepCopy() *ShardConfigList {
	if in == nil {
		return nil
	}
	out := new(ShardConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardConfigSpec) DeepCopyInto(out *ShardConfigSpec) {
	*out = *in
	out.HealthCheckInterval = in.HealthCheckInterval
	out.GracefulShutdownTimeout = in.GracefulShutdownTimeout
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardConfigSpec.
func (in *ShardConfigSpec) DeepCopy() *ShardConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ShardConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardConfigStatus) DeepCopyInto(out *ShardConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardConfigStatus.
func (in *ShardConfigStatus) DeepCopy() *ShardConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ShardConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardInstance) DeepCopyInto(out *ShardInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardInstance.
func (in *ShardInstance) DeepCopy() *ShardInstance {
	if in == nil {
		return nil
	}
	out := new(ShardInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardInstanceList) DeepCopyInto(out *ShardInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShardInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardInstanceList.
func (in *ShardInstanceList) DeepCopy() *ShardInstanceList {
	if in == nil {
		return nil
	}
	out := new(ShardInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShardInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardInstanceSpec) DeepCopyInto(out *ShardInstanceSpec) {
	*out = *in
	if in.HashRange != nil {
		in, out := &in.HashRange, &out.HashRange
		*out = new(HashRange)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardInstanceSpec.
func (in *ShardInstanceSpec) DeepCopy() *ShardInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(ShardInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardInstanceStatus) DeepCopyInto(out *ShardInstanceStatus) {
	*out = *in
	in.LastHeartbeat.DeepCopyInto(&out.LastHeartbeat)
	if in.AssignedResources != nil {
		in, out := &in.AssignedResources, &out.AssignedResources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.HealthStatus != nil {
		in, out := &in.HealthStatus, &out.HealthStatus
		*out = new(HealthStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardInstanceStatus.
func (in *ShardInstanceStatus) DeepCopy() *ShardInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ShardInstanceStatus)
	in.DeepCopyInto(out)
	return out
}
