---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shard-controller.fullname" . }}-manager-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "shard-controller.manager.labels" . | nindent 4 }}
data:
  config.yaml: |
    manager:
      leaderElection:
        enabled: {{ .Values.manager.config.leaderElection.enabled }}
        leaseDuration: {{ .Values.manager.config.leaderElection.leaseDuration }}
        renewDeadline: {{ .Values.manager.config.leaderElection.renewDeadline }}
        retryPeriod: {{ .Values.manager.config.leaderElection.retryPeriod }}
      healthCheck:
        interval: {{ .Values.manager.config.healthCheck.interval }}
        timeout: {{ .Values.manager.config.healthCheck.timeout }}
        failureThreshold: {{ .Values.manager.config.healthCheck.failureThreshold }}
      scaling:
        minShards: {{ .Values.manager.config.scaling.minShards }}
        maxShards: {{ .Values.manager.config.scaling.maxShards }}
        scaleUpThreshold: {{ .Values.manager.config.scaling.scaleUpThreshold }}
        scaleDownThreshold: {{ .Values.manager.config.scaling.scaleDownThreshold }}
        cooldownPeriod: {{ .Values.manager.config.scaling.cooldownPeriod }}
      loadBalancing:
        strategy: {{ .Values.manager.config.loadBalancing.strategy | quote }}
        rebalanceThreshold: {{ .Values.manager.config.loadBalancing.rebalanceThreshold }}
    monitoring:
      metricsPort: {{ .Values.manager.service.metricsPort }}
      healthPort: {{ .Values.manager.service.healthPort }}
      logLevel: {{ .Values.monitoring.logLevel | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shard-controller.fullname" . }}-worker-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "shard-controller.worker.labels" . | nindent 4 }}
data:
  config.yaml: |
    worker:
      heartbeat:
        interval: {{ .Values.worker.config.heartbeat.interval }}
        timeout: {{ .Values.worker.config.heartbeat.timeout }}
      processing:
        batchSize: {{ .Values.worker.config.processing.batchSize }}
        maxConcurrency: {{ .Values.worker.config.processing.maxConcurrency }}
        timeout: {{ .Values.worker.config.processing.timeout }}
      migration:
        timeout: {{ .Values.worker.config.migration.timeout }}
        retryAttempts: {{ .Values.worker.config.migration.retryAttempts }}
        retryDelay: {{ .Values.worker.config.migration.retryDelay }}
    monitoring:
      metricsPort: {{ .Values.worker.service.metricsPort }}
      healthPort: {{ .Values.worker.service.healthPort }}
      logLevel: {{ .Values.monitoring.logLevel | quote }}