apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shard-controller.fullname" . }}-worker
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "shard-controller.worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "shard-controller.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "shard-controller.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shard-controller.worker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: worker
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: {{ include "shard-controller.worker.image" . }}
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        command:
        - /worker
        args:
        - --config=/etc/config/config.yaml
        - --metrics-addr=0.0.0.0:{{ .Values.worker.service.metricsPort }}
        - --health-addr=0.0.0.0:{{ .Values.worker.service.healthPort }}
        - --shard-id=$(POD_NAME)
        ports:
        - name: metrics
          containerPort: {{ .Values.worker.service.metricsPort }}
          protocol: TCP
        - name: health
          containerPort: {{ .Values.worker.service.healthPort }}
          protocol: TCP
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ include "shard-controller.fullname" . }}-worker-config
      terminationGracePeriodSeconds: 60
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}